name: unimarket
description: "Aplicación de mercado online con Clean Architecture + MVVM."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Estado y Arquitectura
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Navegación
  go_router: ^13.0.1

  # Inyección de dependencias
  get_it: ^7.6.4

  # Datos
  dio: ^5.4.0
  shared_preferences: ^2.2.2

  # UI y Utilidades
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.10.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - assets/icons/
    - assets/svgs/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/LOGO_UNIMARKET.png"

